apiVersion: v1
data:
  log4j2.properties: |-
    appenders = FILE, CONSOLE

    appender.CONSOLE.type = Console
    appender.CONSOLE.name = CONSOLE
    appender.CONSOLE.target = SYSTEM_ERR
    appender.CONSOLE.layout.type = PatternLayout
    appender.CONSOLE.layout.pattern = %d{ISO8601} %p [%t] %c - %m%n
    appender.CONSOLE.filter.threshold.type = ThresholdFilter
    appender.CONSOLE.filter.threshold.level = INFO

    appender.FILE.type = RollingFile
    appender.FILE.name = FILE
    appender.FILE.fileName = /stackable/log/spark-history/spark.log4j2.xml
    appender.FILE.filePattern = /stackable/log/spark-history/spark.log4j2.xml.%i
    appender.FILE.layout.type = XMLLayout
    appender.FILE.policies.type = Policies
    appender.FILE.policies.size.type = SizeBasedTriggeringPolicy
    appender.FILE.policies.size.size = 5MB
    appender.FILE.strategy.type = DefaultRolloverStrategy
    appender.FILE.strategy.max = 1
    appender.FILE.filter.threshold.type = ThresholdFilter
    appender.FILE.filter.threshold.level = INFO


    rootLogger.level=INFO
    rootLogger.appenderRefs = CONSOLE, FILE
    rootLogger.appenderRef.CONSOLE.ref = CONSOLE
    rootLogger.appenderRef.FILE.ref = FILE
  security.properties: ""
  spark-defaults.conf: |-
    spark.history.fs.logDirectory hdfs://simple-hdfs:8020/spark-logs

kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-04T14:16:32Z"
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: spark-history
    app.kubernetes.io/managed-by: spark.stackable.tech_history
    app.kubernetes.io/name: spark-k8s
    app.kubernetes.io/role-group: default
    app.kubernetes.io/version: 3.3.0-stackable23.7.0
  name: spark-history-node-default
  namespace: default
  ownerReferences:
  - apiVersion: spark.stackable.tech/v1alpha1
    controller: true
    kind: SparkHistoryServer
    name: spark-history
    uid: dd5e164b-608e-40ee-a9c4-0c3ade4de6ea
  resourceVersion: "14759424"
  uid: f3816795-431a-4210-8a0e-91c13f2c271a
